version: '3.8' # Adicione a vers√£o para compatibilidade
services:
  postgres:
    image: postgres:latest
    container_name: current-hellow
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
